# Generated by Django 4.0.5 on 2022-06-04 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flowers',
            old_name='flower',
            new_name='name',
        ),
    ]
