# Generated by Django 4.0.5 on 2022-06-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_flowers_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowers',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
