# Generated by Django 4.0.5 on 2022-06-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_flowers_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='flowers',
            name='tag',
            field=models.ManyToManyField(to='mysite.tag'),
        ),
    ]
