# Generated by Django 4.0.5 on 2022-06-10 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_rename_slug_tag_sg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='sg',
            new_name='slug',
        ),
    ]
